disabled_rules: # rule identifiers to exclude from running
   - line_length
   
 # - colon
 # - comma
 # - control_statement


opt_in_rules: # some rules are only opt-in
 # - empty_count
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
